import pandas as pd
import numpy as np
data = np.array([['', 'Col1','Col2'],['Fila1',11,22],['Fila2',33,44]])
print(pd.DataFrame(data=data[1:,1:], index=data[1:,0], columns=data[0,1:]))


df = pd.DataFrame(np.array([[1,2,3],[4,5,6]]))
print('DataFrame:')
print(df)

#Crear una serie from scratch
serie = pd.Series(np.array([1,2,3,4,10]))
print('Serie:')
print(serie)

#Información
print('Dimensión:',df.shape)
print('')
print('Cantidad de filas:', df.index)
print('')
print('Estadística de las columnas:')
print(df.describe())
print('')
print('Media de las columnas:')
print(df.mean())
print('')
print('Mediana de las columnas:')
print(df.median())
print('')
print('Cuenta los valores no nulos del df col a col')
print(df.count())
print('')
print('Devuelve el valor máximo de cada col')
print(df.max())
print('')
print('Devuelve el valor mínimo de cada col')
print(df.min())
print('')
print('Desvío standard de las columnas')
print(df.std())
print('')
print('Primera columna')
print(df[0])
print('')
print('Columnas 0 y 1')
print(df[[0,1]])
print('')
print('Fila 1')
print(df.loc[1])
print('')
print(df.iloc[1])
print('')
print('Array con los valores')
print(df.values)